version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'  # Change the port mapping to 5433:5432 or any other available port
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
